/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

@SuppressWarnings("nls")
public final class ABaseBase extends PBase {
    private final LinkedList<PExpr> _params_ = new LinkedList<PExpr>();

    public ABaseBase() {
        // Constructor
    }

    public ABaseBase(
            @SuppressWarnings("hiding") List<?> _params_) {
        // Constructor
        setParams(_params_);

    }

    @Override
    public Object clone() {
        return new ABaseBase(
                cloneList(this._params_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseABaseBase(this);
    }

    public LinkedList<PExpr> getParams() {
        return this._params_;
    }

    public void setParams(List<?> list) {
        for (PExpr e : this._params_) {
            e.parent(null);
        }
        this._params_.clear();

        for (Object obj_e : list) {
            PExpr e = (PExpr) obj_e;
            if (e.parent() != null) {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._params_.add(e);
        }
    }

    @Override
    public String toString() {
        return ""
                + toString(this._params_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._params_.remove(child)) {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        for (ListIterator<PExpr> i = this._params_.listIterator(); i.hasNext(); ) {
            if (i.next() == oldChild) {
                if (newChild != null) {
                    i.set((PExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
