/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import java.util.*;
import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class AElseifBranch extends PBranch
{
    private PExpr _expr_;
    private final LinkedList<PStmt> _stmt_ = new LinkedList<PStmt>();
    private PBranch _branch_;

    public AElseifBranch()
    {
        // Constructor
    }

    public AElseifBranch(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") List<?> _stmt_,
        @SuppressWarnings("hiding") PBranch _branch_)
    {
        // Constructor
        setExpr(_expr_);

        setStmt(_stmt_);

        setBranch(_branch_);

    }

    @Override
    public Object clone()
    {
        return new AElseifBranch(
            cloneNode(this._expr_),
            cloneList(this._stmt_),
            cloneNode(this._branch_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseifBranch(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public LinkedList<PStmt> getStmt()
    {
        return this._stmt_;
    }

    public void setStmt(List<?> list)
    {
        for(PStmt e : this._stmt_)
        {
            e.parent(null);
        }
        this._stmt_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._stmt_.add(e);
        }
    }

    public PBranch getBranch()
    {
        return this._branch_;
    }

    public void setBranch(PBranch node)
    {
        if(this._branch_ != null)
        {
            this._branch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._branch_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._stmt_)
            + toString(this._branch_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._stmt_.remove(child))
        {
            return;
        }

        if(this._branch_ == child)
        {
            this._branch_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        for(ListIterator<PStmt> i = this._stmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._branch_ == oldChild)
        {
            setBranch((PBranch) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
