/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import java.util.*;
import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class AMultiParam extends PParam
{
    private final LinkedList<PParam> _param_ = new LinkedList<PParam>();

    public AMultiParam()
    {
        // Constructor
    }

    public AMultiParam(
        @SuppressWarnings("hiding") List<?> _param_)
    {
        // Constructor
        setParam(_param_);

    }

    @Override
    public Object clone()
    {
        return new AMultiParam(
            cloneList(this._param_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiParam(this);
    }

    public LinkedList<PParam> getParam()
    {
        return this._param_;
    }

    public void setParam(List<?> list)
    {
        for(PParam e : this._param_)
        {
            e.parent(null);
        }
        this._param_.clear();

        for(Object obj_e : list)
        {
            PParam e = (PParam) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._param_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._param_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._param_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PParam> i = this._param_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParam) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
