/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class TTbase extends Token
{
    public TTbase()
    {
        super.setText("base");
    }

    public TTbase(int line, int pos)
    {
        super.setText("base");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTbase(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTbase(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTbase text.");
    }
}
